#!/bin/bash

set -euo pipefail


build_agenda() {
  local -r temp=$1
  pushd /opt/today/spl

  for proj in project-*.md; do
    echo -e "\n&gt; **${proj%.md}**\n" >> "${temp}"
    cat "${proj}" >> "${temp}"
  done

  popd
  echo "${temp}"
}

temp=$(mktemp)
build_agenda "${temp}"
[[ -f ./agenda.md ]] && diff ./agenda.md "${temp}" && exit 0
cp -f "${temp}" ./agenda.md
node mkd2slack.js

exit 0
